### ISSUE TITLE
How to login with ParentVue login/pw?

### ISSUE THREAD

**Issue by gwynnebaer** [kajchang/StudentVueApp-Docs#3]
I have a valid login and password as a parent. Can I use this to login or do I need my student's login/pw?

The "domain" for our school's use may be non-standard:
https://myvue.cascadetech.org/hillsboro/
I put "myvue.cascadetech.org/hillsboro" and the instantiation does not initially fail:

`from studentvue import StudentVue`
`sv = StudentVue('parentuser', 'parentPW', 'myvue.cascadetech.org/hillsboro/',1)`
`print(sv.get_calendar())`

returns (see attached)
[debug.txt](https://github.com/StudentVue/docs/files/5869047/debug.txt)

**Comment by kaijchang** [comment]
@gwynnebaer Sorry I never saw this, my intuition is that the Python client is not compatible with parent accounts.
