### ISSUE TITLE
How to access Course History?

### ISSUE THREAD

**Issue by avighnash** [kajchang/StudentVueApp-Docs#4]
In StudentVUE there are tabs for Course History (which includes information like GPU and credit completion), and I was wondering if it was possible to get that information through this API.

**Comment by kaijchang** [comment]
@avi2k4 Thanks for opening this issue!
Each school district has different features that are disabled / enabled within the app and I only documented the features that were enabled by my school district.

It is possible to determine the routes yourself, the way that I do it is using an app called [Burp Suite](https://portswigger.net/burp) to intercept traffic as I use the app.

After you install Burp Suite, you can follow this guide to configure your iOS device: https://portswigger.net/support/configuring-an-ios-device-to-work-with-burp

I'm not actively working on this project anymore but I hope this helps! Feel free to let me know if you figure it out or need any help.

**Comment by KTibow** [comment]
For anyone else looking for how to access course history:
- Get an `EncyToken` with the `TokenForClassWebSite` method
- Simply visit `/PXP2_CourseHistory.aspx?token=[your token]`
